[package]
name = "shangria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
halo2_proofs = { git = "https://github.com/chaosma/halo2", package="halo2_proofs", branch="pse" }
ff = "0.13"
group = "0.13"
# pasta_curves = "0.5"
sha3 = "0.8.2"
rayon = "1.5.3"
num-bigint = "0.4.3"

rand_core = { version = "0.6", default-features = false }
halo2curves = { git = 'https://github.com/privacy-scaling-explorations/halo2curves', tag = "0.3.2" }

poseidon = { git = "https://github.com/privacy-scaling-explorations/poseidon", rev = "807f8f555313f726ca03bdf941f798098f488ba4" }

[dev-dependencies]
prettytable-rs = "0.10.0"

[patch."https://github.com/chaosma/halo2"]
halo2_proofs = { path = "/Users/chao/opensource/halo2/halo2/halo2_proofs" }
