[package]
name = "shangria"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
halo2_proofs = { git = "https://github.com/chaosma/zcash-halo2", package="halo2_proofs" }
ff = "0.13"
group = "0.13"
pasta_curves = "0.5"
sha3 = "0.8.2"
rayon = "1.5.3"


